SELECT
    HEX(SIGNATURE),
    WRITE_PROTECTION,
    HEX(HMAC_KEY),
    FILE_NAME,
    HEX(HMAC_VALUE),
    DATETIME(START_TIME, 'unixepoch'),
    DATETIME(COMPLETION_TIME, 'unixepoch'),
    REPORTED_SIZE,
    WRITTEN_SIZE
FROM
    MAIN;
